"""Static-site generator for the Kim Lab website.

Reads Markdown from content/ and writes flat HTML pages at the site root.
Standard library only; no JavaScript is emitted.

Usage (from anywhere):
    python3 scripts/build.py              # build all pages
    python3 scripts/build.py --check      # exit 1 if any built page is stale
    python3 scripts/build.py --serve      # build, then serve on 127.0.0.1:8000
    python3 scripts/build.py --serve 9000 --bind 0.0.0.0
    python3 scripts/build.py --watch --serve   # rebuild on every .md save

Supported content syntax (see scripts/README.md for details):
    optional front matter between `---` lines (title, subtitle, description)
    ## Section / ### Subsection      (a leading `# Title` line is ignored)
    - or * bullet lists, 1. numbered lists
    **bold**, *italic*, _italic_, `code`, [text](url)
    ![alt](src) on its own line      -> full-width banner image
    @member{name=, email=, bio=, photo=}
    @grant{title=, funder=, years=, role=, note=}
    any other @type{key, field={...}} -> BibTeX citation
"""

import argparse
import datetime
import functools
import html
import http.server
import os
import re
import subprocess
import sys
import threading
import time

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

SITE_TITLE = 'The Kim Lab @ Princeton EEB'
OWNER = 'Bernard Y. Kim'
PI_SURNAME = 'Kim'             # bolded in author lists

# base.css holds layout; the theme file holds fonts and colors only.
# Swap THEME to 'theme-mono.css' for the original all-monospace look.
STYLESHEETS = ['base.css', 'theme-refined.css']

# Ordered nav. Per-page title/subtitle/description come from each file's front
# matter; these are fallbacks used when front matter is absent.
PAGES = [
    ('index', 'Home'),
    ('research', 'Research'),
    ('publications', 'Publications'),
    ('members', 'Members'),
    ('join-us', 'Join Us'),
]
DEFAULT_SUBTITLE = 'Computational Biology & Evolutionary Genomics'
DEFAULT_DESCRIPTION = ('The Kim Lab studies evolutionary and population genomics '
                       'in the Department of Ecology and Evolutionary Biology at '
                       'Princeton University.')

GENERATED_MARK = '<!-- GENERATED by scripts/build.py from content/{page}.md; do not edit by hand. -->'


# ---------------------------------------------------------------------------
# Inline Markdown
# ---------------------------------------------------------------------------

_STASH_RE = re.compile(r'\x00(\d+)\x00')


def inline(text):
    """Escape HTML, then convert inline Markdown to HTML.

    Code spans and link URLs are stashed behind placeholder tokens before the
    emphasis rules run, so underscores or asterisks inside URLs and code are
    never treated as emphasis.
    """
    text = html.escape(text, quote=False)
    stash = []

    def keep(fragment):
        stash.append(fragment)
        return f'\x00{len(stash) - 1}\x00'

    text = re.sub(r'`([^`]+)`', lambda m: keep(f'<code>{m.group(1)}</code>'), text)
    text = re.sub(r'\[([^\]]+)\]\(([^)\s]+)\)',
                  lambda m: f'<a href="{keep(m.group(2).replace(chr(34), "&quot;"))}">{m.group(1)}</a>',
                  text)
    text = re.sub(r'\*\*(.+?)\*\*', r'<strong>\1</strong>', text)
    text = re.sub(r'(?<!\*)\*(?![\s*])(.+?)(?<![\s*])\*(?!\*)', r'<em>\1</em>', text)
    text = re.sub(r'(?<!\w)_(?!\s)(.+?)(?<!\s)_(?!\w)', r'<em>\1</em>', text)
    return _STASH_RE.sub(lambda m: stash[int(m.group(1))], text)


# ---------------------------------------------------------------------------
# @-blocks (BibTeX-style records)
# ---------------------------------------------------------------------------

_FIELD_RE = re.compile(r'\s*,?\s*(\w+)\s*=\s*')


def _read_braced(s, pos):
    """Return (content, end) for the balanced {...} group starting at s[pos]."""
    depth = 0
    for j in range(pos, len(s)):
        if s[j] == '{':
            depth += 1
        elif s[j] == '}':
            depth -= 1
            if depth == 0:
                return s[pos + 1:j], j + 1
    raise ValueError(f'unbalanced braces in record near: {s[pos:pos + 40]!r}')


def parse_bibtex(entry):
    """Parse one @type{...} record into a dict of lower-cased fields.

    Brace-aware: nested groups such as title={{FlyCADD}: ...} are read whole,
    and protective inner braces are removed from the value. Also accepts
    "quoted" and bare (e.g. year = 2024) values. The citation key is optional
    so @member{...} blocks without one parse too.
    """
    start = entry.index('{') + 1
    key = re.match(r'\s*([^\s,={}]+)\s*,', entry[start:])
    pos = start + key.end() if key else start
    fields = {}
    while True:
        m = _FIELD_RE.match(entry, pos)
        if not m or m.end() >= len(entry):
            break
        name, pos = m.group(1).lower(), m.end()
        if entry[pos] == '{':
            value, pos = _read_braced(entry, pos)
        elif entry[pos] == '"':
            end = entry.index('"', pos + 1)
            value, pos = entry[pos + 1:end], end + 1
        else:
            bare = re.match(r'[^,}\s]+', entry[pos:])
            value, pos = bare.group(0), pos + bare.end()
        value = value.replace('{', '').replace('}', '')
        fields[name] = ' '.join(value.split())
    return fields


def format_authors(raw, highlight=PI_SURNAME):
    """"Kim, BY and Huber, CD and others" -> "<strong>Kim BY</strong>, Huber CD, et al." """
    out = []
    for author in (a.strip() for a in raw.split(' and ')):
        if not author:
            continue
        if author.lower() == 'others':
            out.append('et al.')
            continue
        if ',' in author:
            last, first = (p.strip() for p in author.split(',', 1))
            name = f'{last} {first}'.strip()
        else:
            name = author
            last = author.split()[-1]
        name = html.escape(name, quote=False)
        out.append(f'<strong>{name}</strong>' if last == highlight else name)
    return ', '.join(out)


def format_citation(fields):
    """Render parsed BibTeX fields as one compact HTML citation."""
    authors = format_authors(fields.get('author', ''))
    year = html.escape(fields.get('year', ''))
    title = inline(fields.get('title', '')).rstrip('.')
    journal = html.escape(fields.get('journal', ''))

    locator = fields.get('volume', '')
    if fields.get('number'):
        locator += f"({fields['number']})"
    if fields.get('pages'):
        locator = f"{locator}: {fields['pages']}" if locator else fields['pages']
    locator = html.escape(locator)

    parts = []
    if authors:
        parts.append(f'<span class="pub-authors">{authors}</span>')
    if year:
        parts.append(f'({year}).')
    citation = ' '.join(parts)
    if title:
        citation += f' {title}.'
    if journal:
        citation += f' <span class="pub-journal">{journal}</span>'
        citation += f' {locator}.' if locator else '.'
    elif locator:
        citation += f' {locator}.'
    if fields.get('note'):
        citation += f' <span class="pub-tag">{inline(fields["note"])}</span>'
    return f'<p class="pub">{citation.strip()}</p>'


def render_member(fields):
    """Member card. Email is plain text (no mailto) to reduce scraping."""
    name = fields.get('name', '')
    photo = fields.get('photo', '')
    if photo:
        img = (f'<img class="member-photo" src="{html.escape(photo)}" '
               f'alt="{html.escape(name)}" loading="lazy">')
    else:
        img = '<div class="image-placeholder">PHOTO</div>'

    info = [f'<h3>{inline(name)}</h3>']
    if fields.get('email'):
        info.append(f'<p class="contact">Email: {inline(fields["email"])}</p>')
    if fields.get('bio'):
        info.append(f'<p class="research-desc">{inline(fields["bio"])}</p>')
    return ('<div class="member-card"><div class="member-flex">'
            f'{img}<div class="member-info">{"".join(info)}</div>'
            '</div></div>')


def render_grant(fields):
    """Funding entry: Title. Funder, years. Role. [note]"""
    text = ''
    if fields.get('title'):
        text += f'<span class="grant-title">{inline(fields["title"])}</span>.'
    meta = ', '.join(inline(fields[k]) for k in ('funder', 'years') if fields.get(k))
    if meta:
        text += f' <span class="pub-journal">{meta}</span>.'
    if fields.get('role'):
        text += f' {inline(fields["role"])}.'
    if fields.get('note'):
        text += f' <span class="pub-tag">{inline(fields["note"])}</span>'
    return f'<p class="pub grant">{text.strip()}</p>'


# @type -> renderer. Anything not listed is rendered as a BibTeX citation.
BLOCK_RENDERERS = {
    'member': render_member,
    'grant': render_grant,
}


# ---------------------------------------------------------------------------
# Front matter and block-level Markdown
# ---------------------------------------------------------------------------

def split_front_matter(text):
    """Return (meta dict, body) from an optional leading --- key: value --- block."""
    meta = {}
    lines = text.split('\n')
    if lines and lines[0].strip() == '---':
        for i in range(1, len(lines)):
            line = lines[i].strip()
            if line == '---':
                return meta, '\n'.join(lines[i + 1:])
            if ':' in line:
                k, v = line.split(':', 1)
                meta[k.strip().lower()] = v.strip()
        raise ValueError('front matter opened with --- but never closed')
    return meta, text


def md_to_html(text):
    lines = text.split('\n')
    out = []
    list_type = None  # None | 'ul' | 'ol'

    def close_list():
        nonlocal list_type
        if list_type:
            out.append(f'</{list_type}>')
            list_type = None

    def open_list(kind):
        nonlocal list_type
        if list_type != kind:
            close_list()
            out.append(f'<{kind}>')
            list_type = kind

    i = 0
    while i < len(lines):
        raw = lines[i]
        line = raw.strip()

        if not line:
            close_list()
        elif line.startswith('@'):
            # Accumulate until braces balance, then dispatch on @type.
            close_list()
            block = raw
            depth = raw.count('{') - raw.count('}')
            while depth > 0 and i + 1 < len(lines):
                i += 1
                block += '\n' + lines[i]
                depth += lines[i].count('{') - lines[i].count('}')
            kind = re.match(r'@(\w+)', line).group(1).lower()
            renderer = BLOCK_RENDERERS.get(kind, format_citation)
            out.append(renderer(parse_bibtex(block)))
        elif m := re.match(r'^!\[([^\]]*)\]\(([^)]+)\)\s*$', line):
            close_list()
            alt, src = html.escape(m.group(1)), html.escape(m.group(2))
            out.append(f'<img class="banner" src="{src}" alt="{alt}" loading="lazy">')
        elif line.startswith('# '):
            close_list()  # page H1 comes from the template
        elif line.startswith('### '):
            close_list()
            out.append(f'<h3 class="subsection-head">{inline(line[4:])}</h3>')
        elif line.startswith('## '):
            close_list()
            out.append(f'<h2 class="section-head">{inline(line[3:])}</h2>')
        elif re.match(r'^[-*] ', line):
            open_list('ul')
            out.append(f'<li>{inline(line[2:])}</li>')
        elif m := re.match(r'^\d+\.\s+', line):
            open_list('ol')
            out.append(f'<li>{inline(line[m.end():])}</li>')
        else:
            close_list()
            out.append(f'<p>{inline(line)}</p>')
        i += 1

    close_list()
    return '\n'.join(out)


# ---------------------------------------------------------------------------
# Page assembly
# ---------------------------------------------------------------------------

TEMPLATE = """<!DOCTYPE html>
{mark}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="{description}">
    <title>{title} | {site_title}</title>
{stylesheets}
</head>
<body>
    <div id="container">
        <header>
            <h1>{site_title}</h1>
            <p class="subtitle">{subtitle}</p>
            <nav>
                <ul>
{nav}
                </ul>
            </nav>
        </header>
        <main>
{content}
        </main>
        <footer>
            <hr>
            <p>&copy; {year} {owner}. Last updated: {updated}.</p>
        </footer>
    </div>
</body>
</html>
"""


def render_nav(current):
    items = []
    for page, label in PAGES:
        attr = ' class="current" aria-current="page"' if page == current else ''
        items.append(f'                    <li><a href="{page}.html"{attr}>{html.escape(label)}</a></li>')
    return '\n'.join(items)


def last_updated(content_dir):
    """Date the content was last changed, not the build time.

    Prefers the last git commit touching content/, so CI builds (where every
    checked-out file has today's mtime) show the real edit date. Falls back to
    file mtimes when git is unavailable or the content has uncommitted edits.
    """
    mtimes = [os.path.getmtime(os.path.join(content_dir, f))
              for f in os.listdir(content_dir) if f.endswith('.md')]
    try:
        dirty = subprocess.run(['git', 'status', '--porcelain', '--', content_dir],
                               capture_output=True, text=True, check=True).stdout.strip()
        if not dirty:
            out = subprocess.run(['git', 'log', '-1', '--format=%cs', '--', content_dir],
                                 capture_output=True, text=True, check=True).stdout.strip()
            if out:
                return datetime.date.fromisoformat(out)
    except (OSError, subprocess.CalledProcessError, ValueError):
        pass
    return datetime.date.fromtimestamp(max(mtimes)) if mtimes else datetime.date.today()


def render_site(root):
    """Return {output filename: html} for every page with a content file."""
    content_dir = os.path.join(root, 'content')
    updated = last_updated(content_dir)
    stylesheets = '\n'.join(f'    <link rel="stylesheet" href="css/{s}">' for s in STYLESHEETS)
    pages = {}
    for page, label in PAGES:
        md_path = os.path.join(content_dir, f'{page}.md')
        if not os.path.exists(md_path):
            continue
        with open(md_path, encoding='utf-8') as f:
            meta, body = split_front_matter(f.read())
        pages[f'{page}.html'] = TEMPLATE.format(
            mark=GENERATED_MARK.format(page=page),
            title=html.escape(meta.get('title', label)),
            site_title=html.escape(SITE_TITLE),
            subtitle=html.escape(meta.get('subtitle', DEFAULT_SUBTITLE)),
            description=html.escape(meta.get('description', DEFAULT_DESCRIPTION)),
            stylesheets=stylesheets,
            nav=render_nav(page),
            content=md_to_html(body),
            year=updated.year,
            owner=html.escape(OWNER),
            updated=f'{updated:%B} {updated.day}, {updated.year}',
        )
    return pages


def write_site(root, pages):
    """Write only pages whose HTML changed, so Dropbox/git see minimal churn."""
    stale = set(check_site(root, pages))
    for name, text in pages.items():
        if name not in stale:
            continue
        with open(os.path.join(root, name), 'w', encoding='utf-8') as f:
            f.write(text)
        print(f'built {name}', flush=True)
    if not stale:
        print('up to date', flush=True)


def check_site(root, pages):
    """Return names of built pages whose on-disk copy differs from the sources."""
    stale = []
    for name, text in pages.items():
        path = os.path.join(root, name)
        try:
            with open(path, encoding='utf-8') as f:
                if f.read() != text:
                    stale.append(name)
        except FileNotFoundError:
            stale.append(name)
    return stale


def serve(root, port, bind, block=True):
    handler = functools.partial(http.server.SimpleHTTPRequestHandler, directory=root)
    httpd = http.server.ThreadingHTTPServer((bind, port), handler)
    print(f'serving {root} at http://{bind}:{port}/', flush=True)
    if not block:
        threading.Thread(target=httpd.serve_forever, daemon=True).start()
        return httpd
    try:
        httpd.serve_forever()
    except KeyboardInterrupt:
        print('\nstopped')
    finally:
        httpd.server_close()


def content_snapshot(content_dir):
    """{filename: (mtime, size)} for every .md file in content/."""
    snap = {}
    for name in os.listdir(content_dir):
        if name.endswith('.md'):
            st = os.stat(os.path.join(content_dir, name))
            snap[name] = (st.st_mtime_ns, st.st_size)
    return snap


def build_once(root):
    """Render and write the site; report errors instead of raising."""
    try:
        write_site(root, render_site(root))
    except (ValueError, OSError) as err:
        # Usually a half-saved file (e.g. unbalanced braces); fixed on next save.
        print(f'build failed: {err}', file=sys.stderr, flush=True)


def watch(root, interval):
    """Rebuild whenever a content/*.md file is added, removed, or modified.

    Polls timestamps rather than using inotify, which does not fire under WSL
    for files on Windows drives (/mnt/*) edited from Windows or synced by Dropbox.
    """
    content_dir = os.path.join(root, 'content')
    last = content_snapshot(content_dir)
    print(f'watching {content_dir} every {interval}s (Ctrl+C to stop)', flush=True)
    while True:
        time.sleep(interval)
        try:
            now = content_snapshot(content_dir)
        except OSError:
            continue  # directory briefly unavailable mid-sync
        if now != last:
            changed = sorted(n for n in now.keys() | last.keys() if now.get(n) != last.get(n))
            print(f'[{time.strftime("%H:%M:%S")}] changed: {", ".join(changed)}', flush=True)
            last = now
            build_once(root)


def main(argv=None):
    parser = argparse.ArgumentParser(description='Build the Kim Lab website.')
    parser.add_argument('--check', action='store_true',
                        help='do not write; exit 1 if any HTML is out of date')
    parser.add_argument('--serve', nargs='?', const=8000, type=int, metavar='PORT',
                        help='build, then serve the site locally (default port 8000)')
    parser.add_argument('--bind', default='127.0.0.1',
                        help='address for --serve (default 127.0.0.1)')
    parser.add_argument('--watch', action='store_true',
                        help='rebuild whenever a content/*.md file changes')
    parser.add_argument('--interval', type=float, default=1.0, metavar='SECONDS',
                        help='polling interval for --watch (default 1)')
    args = parser.parse_args(argv)

    # Site root is the parent of this script's directory.
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

    if args.watch:
        build_once(root)
        httpd = serve(root, args.serve, args.bind, block=False) if args.serve else None
        try:
            watch(root, args.interval)
        except KeyboardInterrupt:
            print('\nstopped')
        finally:
            if httpd:
                httpd.shutdown()
                httpd.server_close()
        return 0

    pages = render_site(root)

    if args.check:
        stale = check_site(root, pages)
        for name in stale:
            print(f'stale: {name}')
        print('up to date' if not stale else 'run scripts/build.py to rebuild')
        return 1 if stale else 0

    write_site(root, pages)
    if args.serve is not None:
        serve(root, args.serve, args.bind)
    return 0


if __name__ == '__main__':
    sys.exit(main())
