"""Regenerate assets/favicon.svg from scripts/favicon_map.txt (16x16 pixel map)."""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
PALETTE = {'B': '#c98f3d', 'D': '#4a3016', 'E': '#c62828', 'W': '#9fb7c9', 'L': '#4a3016'}
OPACITY = {'W': '0.75'}
BACKGROUND = '#f4f4f2'   # site paper colour

rows = open(os.path.join(HERE, 'favicon_map.txt')).read().strip('\n').split('\n')
out = ['<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" shape-rendering="crispEdges">',
       '  <!-- pixel-art Drosophila, dorsal view. Generated by scripts/make_favicon.py -->',
       f'  <rect width="16" height="16" fill="{BACKGROUND}"/>']
for y, row in enumerate(rows):
    for x, c in enumerate(row):
        if c in PALETTE:
            o = f' fill-opacity="{OPACITY[c]}"' if c in OPACITY else ''
            out.append(f'  <rect x="{x}" y="{y}" width="1" height="1" fill="{PALETTE[c]}"{o}/>')
out.append('</svg>')
with open(os.path.join(HERE, '..', 'assets', 'favicon.svg'), 'w') as f:
    f.write('\n'.join(out) + '\n')
print('wrote assets/favicon.svg')
